version: '1'
services:
  backend:
    build:
      context: ./backend  
    ports:
      - "5000:5000" 
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=appdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - MONGO_URI=mongodb://mongo:27017/document_db
    volumes:
      - ./backend:/app
    networks:
      - app-network
    depends_on:
      - postgres
      - mongo
  
  frontend:
    build:
      context: ./frontend  
    ports:
      - "80:80"  
    networks:
      - app-network
    depends_on:
      - backend  


  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=appdb
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017" 
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:

networks:
  app-network:
    driver: bridge
